package com.promoCode.promoCode.entities;

// PromoCode.java

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.time.LocalDate;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class PromoCode {

@Id
@GeneratedValue(strategy= GenerationType.IDENTITY)
// Unique identifier for the promotional code. This is automatically generated by the database.
private Integer idCode;

// The promotional code itself. This is the code that users will enter to receive a discount.
private String code;

// The discount associated with the promotional code. This is a percentage value (e.g., a discount of 20% is represented as 20.0).
private double discount;

// The start date of the promotional code's validity period. The code cannot be used before this date.
private LocalDate startDate;

// The end date of the promotional code's validity period. The code cannot be used after this date.
private LocalDate endDate;

// A counter for tracking the number of times the promotional code has been used.
private int usageCount;

}
